### PR TITLE
Fix no site names for all functions

### LINKED ISSUE #76: fd_dis gives error if site x species matrix does not have row names
I ran into an issue using `fd_dis()` when my site x species matrix doesn't have row names. For my purposes, I cannot force my site x species matrices to have row names as they are contained within a simulation matrix (class `simmat`). I expect this could be an issue for future users as well. 

An easy fix would be to either just force "Site" in the return dataframe from the `fd_dis()` function to be `1:nrow` :

`data.frame(site = 1:nrow(sp_com), FDis = fdis_site, row.names = NULL)`

or use an `if` statement

`if(is.null(rownames(sp_com))) { rownames(sp_com) <- 1:nrow(sp_com) } `
`data.frame(site = rownames(sp_com), FDis = fdis_site, row.names = NULL)`

### PR DESCRIPTION
**Pull request by Rekyt**
Fixes #76

### CODE REVIEW

File: R/fd_fdis.R [hunk 1]
```diff
@@ -62,6 +65,12 @@ fd_fdis <- function(traits, sp_com) {
 
   }
 
+  if (is.null(rownames(sp_com))) {
+
+    rownames(sp_com) <- paste0("s", seq_len(nrow(sp_com)))
+
+  }
```
Comment (Bisaloo) [inline R/fd_fdis.R:72]: My only concern here is that this happens after we already dropped some columns from `sp_com`. So `s1`, s2`, etc. may not necessarily match with the first, second, etc. rows of `sp_com`.

Is this an issue?

**Review by Bisaloo — APPROVED** [review]
